[pytest]
minversion = 6.0
addopts = --strict-markers --tb=short --cov=src --cov-report=term-missing -vv
testpaths = tests
pythonpath = . src
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    asyncio: mark test functions as requiring asyncio
    authenticator: mark tests related to authenticator functionality
